# Generated by Django 5.2.7 on 2025-11-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='book_images/')),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='book_files/')),
                ('author', models.CharField(max_length=100)),
                ('number_of_views', models.IntegerField(default=0)),
            ],
        ),
    ]
